# Generated by Django 6.0a1 on 2025-10-09 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(max_length=36, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_item_id', models.CharField(max_length=36, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_work_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_work_items', to='core.workitem')),
                ('to_work_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_work_items', to='core.workitem')),
            ],
        ),
    ]
